### ISSUE TITLE
Bug in CLI argument definition prevents `__main__.py` from starting.

### ISSUE THREAD

**Issue by awalls-cx18** [paullockaby/enphase-proxy#51]
This CLI argument definition puts the value for the `--bind` argument in a variable called `args.address`:

[https://github.com/paullockaby/enphase-proxy/blob/6d7c53e081c28301c620500fbc56f2f1f6b49609/src/enphase_proxy/__main__.py#L32](https://github.com/paullockaby/enphase-proxy/blob/6d7c53e081c28301c620500fbc56f2f1f6b49609/src/enphase_proxy/__main__.py#L32)

But when used to run the main program, a variable called `args.bind` is used, and it does not exist:

[https://github.com/paullockaby/enphase-proxy/blob/6d7c53e081c28301c620500fbc56f2f1f6b49609/src/enphase_proxy/__main__.py#L51](https://github.com/paullockaby/enphase-proxy/blob/6d7c53e081c28301c620500fbc56f2f1f6b49609/src/enphase_proxy/__main__.py#L51)

This causes the program to fail to run.

Here is the invocation and traceback:

```
awalls@dales:~/git_clones/paullockaby/enphase-proxy/src/enphase_proxy$ poetry run python3 -m enphase_proxy -v -b 127.0.0.1 -p 8080
[2024-07-28 18:56:30,478] INFO     - loading configuration from '/home/awalls/git_clones/paullockaby/enphase-proxy/src/configurations/development.conf'
[2024-07-28 18:56:30,479] INFO     - starting web application in 'development' mode with version 0.0.0
[2024-07-28 18:56:30,482] DEBUG    - <QuartRule '/_/health' (OPTIONS, GET, HEAD) -> health>
[2024-07-28 18:56:30,482] DEBUG    - <QuartRule '/' (OPTIONS, POST, GET, HEAD) -> proxy>
[2024-07-28 18:56:30,482] DEBUG    - <QuartRule '/<path>' (OPTIONS, POST, GET, HEAD) -> proxy>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/awalls/git_clones/paullockaby/enphase-proxy/src/enphase_proxy/__main__.py", line 51, in <module>
    host=args.bind,
         ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'bind'
```

**Comment by plockaby** [comment]
Thank you very much for finding this and the detailed write up! I should probably write some tests at some point to detect things like this :(

I've pushed the updated fix to main. It's going to be a few days at least before I can make a release with a new container, though. (I think you can see that I'm doing a lot of CI work across my repositories and I want to finish that first.)

Let me know if you find anything else. Thanks!

**Comment by awalls-cx18** [comment]
Thanks and you're welcome.

I'm going to have Permission to Operate from my local utility within the week, so I'll be setting up Prometheus to scrape my IQ5's IQ Gateway.  I'll let you know if I find anything else.
